# sudo is required for docker
sudo: required

language: go

services:
    - docker

before_install:
    docker pull mysql:5.6


# With the "docker" tag enabled,
# the mysql:5.6 docker container will be started
# and the mysql tests will connect to this container
script: go test -v -tags docker  ./...


