# sudo is required for docker
sudo: required

language: go

services:
    - docker

install:
    - docker pull mysql:5.6
    - go get github.com/golang/lint/golint
    - go get github.com/kisielk/errcheck


# With the "docker" tag enabled,
# the mysql:5.6 docker container will be started
# and the mysql tests will connect to this container
#
script:
    - diff -u <(echo -n) <(gofmt -d `find . -name '*.go' | grep -Ev '/vendor/|/migration'`)
    - go list ./... | grep -Ev '/vendor/|/migration' | xargs -L1 golint
    - go vet `go list ./... | grep -v /vendor/`
    - errcheck -ignore 'io:Close' -ignoretests `go list ./... | grep -v /vendor/`
    - go test -v -tags docker  ./...

